[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "ship protect endorse arrow because path meat immune quote drink fluid state mask burger divert upset arena body column all tray sing viable arctic"


